version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: stockPro_postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YourStrongPassword123!
      - POSTGRES_DB=StockManagementDb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - stock-network

  backend:
    image: mcr.microsoft.com/dotnet/sdk:8.0 
    container_name: stockPro_backend
    working_dir: /app
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080 
      # This tells .NET exactly where the DB is in the Docker network
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=StockManagementDb;Username=postgres;Password=YourStrongPassword123!
    volumes:
      - ./backend:/app
    command: dotnet watch run --project StockManagement-Api.csproj --non-interactive --urls "http://0.0.0.0:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - stock-network

  frontend:
    image: node:20-alpine
    container_name: stockPro_frontend
    working_dir: /app
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # Run npm install first to make sure 'ng' exists in the volume
    command: >
      sh -c "npm install && npx ng serve --host 0.0.0.0 --port 4200 --poll 2000 --disable-host-check"
    networks:
      - stock-network

networks:
  stock-network:
    driver: bridge

volumes:
  postgres_data: